import { useMemo, useState } from 'react'
import { ArrowRight, BrainCircuit, Clock3, Dumbbell, RefreshCw, SlidersHorizontal, Sparkles } from 'lucide-react'
import { Button } from '../../design/components/Button'
import { Card } from '../../design/components/Card'
import { assembleWorkout } from '../../domain/training/assembleWorkout'
import type { TrainingSplit } from '../../domain/models'
import { ActiveWorkoutPage } from './ActiveWorkoutPage'
import { CoachSourceToggle } from './CoachSourceToggle'
import './training.css'

const splits: {id:TrainingSplit;label:string}[]=[{id:'push',label:'Push'},{id:'pull',label:'Pull'},{id:'legs',label:'Legs'},{id:'upper',label:'Upper'},{id:'lower',label:'Lower'},{id:'full-body',label:'Full body'},{id:'fresh',label:'Fresh muscles'}]

export function TrainPage() {
  const [split,setSplit]=useState<TrainingSplit>('push'); const [source,setSource]=useState<'deterministic'|'ai'>('deterministic'); const [active,setActive]=useState(false)
  const plan=useMemo(()=>assembleWorkout({split,durationMinutes:48,capabilities:['bodyweight','dumbbell','flat-bench','incline-bench','seated-bench','low-cable','high-cable','twister','treadmill'],excludedExerciseIds:[],readiness:{chest:94,triceps:82,'front-delts':88,'side-delts':91,biceps:66,lats:71,quadriceps:44,glutes:78},variability:'balanced',seed:`demo:${split}`}),[split])
  if(active)return <ActiveWorkoutPage onFinish={()=>setActive(false)}/>
  return <div className="train-page"><header className="page-header"><div><p className="eyebrow">Adaptive training</p><h1>Train what’s ready.</h1><p className="muted">Every movement fits your equipment, recovery and available time.</p></div><Button variant="secondary"><SlidersHorizontal size={18}/> 48 min</Button></header><div className="train-controls"><CoachSourceToggle source={source} onChange={setSource}/><div className="split-scroll">{splits.map(item=><button key={item.id} onClick={()=>setSplit(item.id)} className={split===item.id?'active':''}>{item.label}</button>)}</div></div>{source==='ai'&&<Card className="ai-notice"><span className="icon-tile"><BrainCircuit/></span><div><strong>AI Coach is ready when your server key is connected.</strong><p>It can propose an alternative, then Fitile checks every exercise against the same equipment and recovery rules.</p></div><Button variant="secondary">Configure</Button></Card>}<Card accent className="plan-summary"><div><p className="eyebrow eyebrow--lime">{source==='ai'?'AI alternative preview':'Deterministic coach'}</p><h2>{split==='push'?'Dumbbell push':`${splits.find(item=>item.id===split)?.label} session`}</h2><p>{plan.explanation}</p></div><div className="plan-meta"><span><Clock3 size={16}/> {plan.durationMinutes} min</span><span><Dumbbell size={16}/> {plan.exercises.length} exercises</span><span><Sparkles size={16}/> 86% ready</span></div><Button onClick={()=>setActive(true)}>Start workout <ArrowRight size={18}/></Button></Card><div className="exercise-list-heading"><div><p className="eyebrow">Today’s work</p><h2>{plan.exercises.length} exercises</h2></div><Button variant="ghost"><RefreshCw size={16}/> Regenerate</Button></div><div className="plan-exercises">{plan.exercises.map((item,index)=><Card key={item.exercise.id} className="plan-exercise"><span className="exercise-number">{String(index+1).padStart(2,'0')}</span><div className="plan-exercise__body"><h3>{item.exercise.name}</h3><p>{item.sets} × {item.repRange[0]}–{item.repRange[1]} {item.suggestedWeightKg?`· ${item.suggestedWeightKg} kg`:''}</p><small>{item.reasons[0]}</small></div><button className="round-button" aria-label={`Swap ${item.exercise.name}`}><RefreshCw size={16}/></button></Card>)}</div><p className="fine-print">Recommendations are training estimates. Stop for sharp pain, dizziness, chest pain or unusual shortness of breath.</p></div>
}
