import { useRef, useState } from 'react'
import { Cloud, Download, FileJson, RotateCcw, Shield, Trash2, Upload } from 'lucide-react'
import { Button } from '../../design/components/Button'
import { Card } from '../../design/components/Card'
import { createArchive, type AccountSnapshot } from '../../domain/export/createArchive'
import { createCsvBundle } from '../../domain/export/createCsvBundle'
import { restoreArchive } from '../../domain/export/restoreArchive'
import { saveTextFile } from '../../integrations/download/saveFile'
import { useAuth } from '../auth/authContext'

const demoSnapshot:AccountSnapshot={workouts:[{date:'2026-08-27',name:'Dumbbell push',durationMinutes:48,volumeKg:3820}],meals:[{date:'2026-08-28',meal:'Breakfast',food:'Protein oats',kcal:486}],activities:[{date:'2026-08-28',type:'Walking',minutes:42,estimatedKcal:218}],measurements:[{date:'2026-08-28',weightKg:79.6}],settings:{goal:'fat-loss',calorieTarget:2000,proteinTargetG:150,units:'metric'},equipment:[{name:'Adjustable dumbbells',minKg:5,maxKg:25},{name:'Adjustable bench'},{name:'Treadmill'}]}

export function DataOwnershipPage(){const auth=useAuth();const fileRef=useRef<HTMLInputElement>(null);const[restoreMessage,setRestoreMessage]=useState('');const exportJson=()=>saveTextFile(`fittile-export-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(createArchive(demoSnapshot),null,2),'application/json');const exportCsv=()=>{for(const[name,content]of Object.entries(createCsvBundle(demoSnapshot)))saveTextFile(name,content,'text/csv')};const restore=async(file?:File)=>{if(!file)return;try{const data=restoreArchive(JSON.parse(await file.text()));setRestoreMessage(`Archive ready: ${data.workouts.length} workout, ${data.meals.length} meal and ${data.activities.length} activity records.`)}catch{setRestoreMessage('This file is not a compatible Fitile V1 archive. No data was changed.')}};return <section className="settings-grid"><Card><span className="icon-tile"><Cloud/></span><p className="eyebrow">Synchronization</p><h2>{auth.status==='demo'?'Demo mode':'Fitile cloud'}</h2><p className="muted">{auth.status==='demo'?'This preview is local. Add Supabase settings to enable private Google sign-in and automatic cross-device sync.':'All account records are scoped to your signed-in identity.'}</p></Card><Card><span className="icon-tile"><FileJson/></span><p className="eyebrow">Complete archive</p><h2>Export everything</h2><p className="muted">Versioned JSON for full restore, plus readable CSV tables.</p><div className="data-actions"><Button onClick={exportJson}><Download size={16}/> JSON</Button><Button variant="secondary" onClick={exportCsv}>CSV files</Button></div></Card><Card><span className="icon-tile"><RotateCcw/></span><p className="eyebrow">Restore</p><h2>Bring your data back</h2><p className="muted">Fitile validates the archive before applying any records.</p><input ref={fileRef} hidden type="file" accept="application/json,.json" onChange={(event)=>void restore(event.target.files?.[0])}/><Button variant="secondary" onClick={()=>fileRef.current?.click()}><Upload size={16}/> Choose archive</Button>{restoreMessage&&<p className="restore-message" role="status">{restoreMessage}</p>}</Card><Card><span className="icon-tile"><Shield/></span><p className="eyebrow">Ownership</p><h2>Your data stays yours.</h2><p className="muted">Food photos are removed after analysis by default. You can export, restore, sign out or delete your account.</p></Card><Card className="settings-wide danger-zone"><Trash2/><div><h2>Delete synchronized account</h2><p className="muted">Requires fresh sign-in and typed confirmation. This cannot be undone after server deletion.</p></div><Button variant="ghost" disabled={auth.status==='demo'}>Delete account</Button></Card></section>}
