import { useState } from 'react'
import { Clock3, Info, TrendingUp } from 'lucide-react'
import { Card } from '../../design/components/Card'
import { ProgressRing } from '../../design/components/ProgressRing'
import { muscleById } from '../../domain/catalog/muscles'
import type { MuscleId } from '../../domain/models'
import { MuscleMap } from './MuscleMap'
import { SorenessCheckIn } from './SorenessCheckIn'
import './recovery.css'

const readiness: Partial<Record<MuscleId,number>>={chest:28,'front-delts':44,'side-delts':82,'rear-delts':75,triceps:36,biceps:92,forearms:84,'upper-back':67,lats:70,'lower-back':58,abs:91,obliques:78,glutes:88,quadriceps:42,hamstrings:55,calves:74}

export function RecoveryPage(){const[selected,setSelected]=useState<MuscleId>('chest');const value=readiness[selected]??100;return <div className="recovery-page"><header className="page-header"><div><p className="eyebrow">Recovery</p><h1>Listen to the work.</h1><p className="muted">Readiness gradually returns as training fatigue decays.</p></div><ProgressRing value={68} label="Whole body readiness" size={76} color="var(--recovering)"/></header><div className="recovery-layout"><Card className="map-card"><div className="recovery-legend"><span><i className="fresh"/>Fresh</span><span><i className="recovering"/>Recovering</span><span><i className="fatigued"/>Fatigued</span></div><MuscleMap readiness={readiness} selected={selected} onSelect={setSelected}/><p className="fine-print">Color is paired with percentages and state labels for accessibility.</p></Card><div className="recovery-details"><Card><p className="eyebrow">Selected muscle</p><div className="selected-readiness"><div><h2>{muscleById[selected].name}</h2><strong>{value}% ready</strong></div><ProgressRing value={value} label={`${muscleById[selected].name} readiness`} size={72} color={value>=75?'var(--fresh)':value>=40?'var(--recovering)':'var(--fatigued)'}/></div><div className="recovery-stat"><Clock3/><div><strong>{value<75?'About 32 hours to fresh':'Ready to train'}</strong><span>Estimated from your recent training load</span></div></div><div className="contributors"><p className="eyebrow">What affected this</p>{selected==='chest'?<article><span className="event-dot"/><div><strong>Dumbbell bench press · 3 sets</strong><small>Yesterday, 18:42 · high effort</small></div><b>−72</b></article>:<article><span className="event-dot amber"/><div><strong>Recent weekly volume</strong><small>Training load contribution</small></div><b>−{100-value}</b></article>}</div></Card><Card><div className="info-title"><Info/><div><h2>How readiness works</h2><p>Sets create estimated fatigue for primary and secondary muscles. It then decays with time and your feedback.</p></div></div><div className="recovery-stat"><TrendingUp/><div><strong>Transparent, not physiological</strong><span>You can override any value when your body feels different.</span></div></div></Card><Card><SorenessCheckIn muscleId={selected}/></Card></div></div></div>}
